#Default the security credentials to call the config service. Override these
#for your deployment.
direct:
  webservices:
    security:
      basic:
        user:
          name: admin
          password: d1r3ct;
          
  config:
    service:
      url: http://localhost:8080/config-service          